### ISSUE TITLE
Densenet 169 doesn't load the example.

### ISSUE THREAD

**Issue by andimarafioti** [hassony2/inflated_convnets_pytorch#7]
When I try to load the example with densenet 169 I get the following traceback:

` 
python inflate_densenet.py --densenet_nb 169

Traceback (most recent call last):
File "/Users/andimarafioti/Documents/code/inflated_convnets_pytorch/inflate_densenet.py", line 113, in <module>
    run_inflater(args)
  File "/Users/andimarafioti/Documents/code/inflated_convnets_pytorch/inflate_densenet.py", line 43, in run_inflater
    i3densenet = I3DenseNet(
  File "/Users/andimarafioti/Documents/code/inflated_convnets_pytorch/src/i3dense.py", line 15, in __init__
    self.features, transition_nb = inflate_features(
  File "/Users/andimarafioti/Documents/code/inflated_convnets_pytorch/src/i3dense.py", line 121, in inflate_features
    _DenseLayer3d(
  File "/Users/andimarafioti/Documents/code/inflated_convnets_pytorch/src/i3dense.py", line 53, in __init__
    self.add_module('padding.1', pad_time)
  File "/Users/andimarafioti/miniforge3/envs/torchless/lib/python3.9/site-packages/torch/nn/modules/module.py", line 380, in add_module
    raise KeyError("module name can't contain \".\", got: {}".format(name))
KeyError: 'module name can\'t contain ".", got: padding.1'
`

**Comment by andimarafioti** [comment]
According to https://github.com/pytorch/vision/issues/809, "." are no longer allowed in module names. 

Changing the "." to "-" fixes the issue.
